{{- if .Values.ingress.enabled -}}
{{- $svcPort := .Values.maps.service.port -}}
{{- $name := include "workadventure.maps.name" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
  {{- with merge .Values.ingress.annotations .Values.maps.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- if not .Values.maps.ingress.rules }}
    - host: {{ printf "%s.%s" $.Values.maps.subdomain $.Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
    {{- range .Values.maps.ingress.rules }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . | quote}}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $svcPort }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.maps.ingress.tls }}
  tls:
    {{- range .Values.maps.ingress.tls }}
    - hosts:
        {{- if not .hosts }}
        - {{ printf "%s.%s" $.Values.maps.subdomain $.Values.domain }}
        {{- end }}
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
